title: Coding, Creativity, and Confidence in AI-Era project
email: ccc-ai@glasgow.ac.uk
description: >-
  Coding, Creativity, and Confidence in AI-Era project aims to understand and improve coding education across disciplines to equip students with fundamental computational thinking skills while the flood of AI-enabled tools are being introduced into the society thus the learning environments. 
baseurl: "/"
url: "https://CCC-AI-era.github.io"
github_username: yryo617

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-textile-converter

include: ['_pages','_pages/events']

header_pages:
  - people.md
  - _posts/
  - _pages/events/index.md